name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-daily:focal
          - ubuntu-daily:jammy
          - ubuntu-daily:kinetic
          - ubuntu-daily:lunar
    steps:
    - uses: actions/checkout@v2
    - name: run
      run: sudo ./scripts/test-in-lxd.sh ${{ matrix.image }} "make check"
  lint:
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        image:
          - ubuntu-daily:jammy    # match the core snap we're running against
          - ubuntu-daily:lunar    # latest
    steps:
    - uses: actions/checkout@v2
    - name: lint
      run: sudo ./scripts/test-in-lxd.sh ${{ matrix.image }} "make lint"
