name: VM Tests

on:
  push:
    paths-ignore:
      - 'doc/**'
  pull_request:
    paths-ignore:
      - 'doc/**'

jobs:
  vmtest:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4

      - name: install vmtest dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pytest virtinst fuseiso fuse3 libvirt-clients libvirt-daemon libvirt-daemon-driver-qemu libvirt-daemon-system openssh-client

      - name: download ISO
        run: |
          cd ${{ runner.temp }}
          wget -nv -O stonking-live-server-amd64.iso \
            https://cdimage.ubuntu.com/ubuntu-server/daily-live/current/stonking-live-server-amd64.iso
          wget -nv -O SHA256SUMS \
            https://cdimage.ubuntu.com/ubuntu-server/daily-live/current/SHA256SUMS
          sha256sum -c SHA256SUMS --ignore-missing
          ls -lh stonking-live-server-amd64.iso

      - name: run vmtest
        run: |
          cd ${{ github.workspace }}
          sudo env PYTHONPATH=. pytest-3 --iso=${{ runner.temp }}/stonking-live-server-amd64.iso -k test_bios_direct vmtests

      - name: cleanup
        if: always()
        run: rm -f ${{ runner.temp }}/stonking-live-server-amd64.iso
